language: python

sudo: false

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  # different connection classes to test
  - TEST_ES_CONNECTION=Urllib3HttpConnection
  - TEST_ES_CONNECTION=RequestsHttpConnection

install:
  - wget -O /tmp/es-snap.zip "https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.elasticsearch.distribution.zip&a=elasticsearch&e=zip&v=5.0.0-SNAPSHOT"
  - unzip /tmp/es-snap.zip -d /tmp/
  - mv /tmp/elasticsearch-5.0.0-SNAPSHOT /tmp/elasticsearch
  - /tmp/elasticsearch/bin/elasticsearch -E script.inline=true -E path.repo=/tmp -E repositories.url.allowed_urls='http://*' -E node.attr.testattr=test
  - git clone https://github.com/elastic/elasticsearch.git ../elasticsearch
  - pip install .

script:
  - python setup.py test

notifications:
  email:
    recipients:
      - honza.kral@gmail.com
