language: python

services:
  - docker

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

env:
  # different connection classes to test
  - TEST_ES_CONNECTION=Urllib3HttpConnection
  - TEST_ES_CONNECTION=RequestsHttpConnection

before_install:
  - docker run --rm --detach --publish 9200:9200 --env "discovery.type=single-node" -e path.repo=/tmp -e "repositories.url.allowed_urls=http://*" -e node.attr.testattr=test  -e node.name=test  --name elasticsearch docker.elastic.co/elasticsearch/elasticsearch:7.4.0

install:
  - git clone https://github.com/elastic/elasticsearch.git ../elasticsearch
  - pip install .[develop]

script:
  - python setup.py test
