language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"

env:
  # different connection classes to test
  - TEST_ES_CONNECTION=Urllib3HttpConnection
  - TEST_ES_CONNECTION=RequestsHttpConnection

install:
  - mkdir /tmp/elasticsearch
  - wget -O - http://s3-us-west-2.amazonaws.com/build.elasticsearch.org/origin/master/nightly/JDK6/elasticsearch-latest-SNAPSHOT.tar.gz | tar xz --directory=/tmp/elasticsearch --strip-components=1
  - /tmp/elasticsearch/bin/plugin -install elasticsearch/elasticsearch-transport-memcached/2.0.0.RC1
  - git clone https://github.com/elasticsearch/elasticsearch.git ../elasticsearch
  - pip install .

before_script:
  - /tmp/elasticsearch/bin/elasticsearch -d -D es.path.data=/tmp -D es.gateway.type=none -D es.index.store.type=memory -D es.discovery.zen.ping.multicast.enabled=false -Des.node.bench=true

script:
  - python setup.py test

